// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package arcidx

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FileNode struct {
	_tab flatbuffers.Table
}

func GetRootAsFileNode(buf []byte, offset flatbuffers.UOffsetT) *FileNode {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FileNode{}
	x.Init(buf, n+offset)
	return x
}

func FinishFileNodeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsFileNode(buf []byte, offset flatbuffers.UOffsetT) *FileNode {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &FileNode{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedFileNodeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *FileNode) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FileNode) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *FileNode) PathId() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FileNode) MutatePathId(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *FileNode) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *FileNode) OffsetHeader() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FileNode) MutateOffsetHeader(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func (rcv *FileNode) OffsetData() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FileNode) MutateOffsetData(n uint64) bool {
	return rcv._tab.MutateUint64Slot(10, n)
}

func (rcv *FileNode) Size() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FileNode) MutateSize(n uint64) bool {
	return rcv._tab.MutateUint64Slot(12, n)
}

func (rcv *FileNode) Mtime() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FileNode) MutateMtime(n int64) bool {
	return rcv._tab.MutateInt64Slot(14, n)
}

func (rcv *FileNode) MetadataId() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FileNode) MutateMetadataId(n uint32) bool {
	return rcv._tab.MutateUint32Slot(16, n)
}

func (rcv *FileNode) Xattrs(obj *Xattr, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *FileNode) XattrsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *FileNode) Acl(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *FileNode) AclLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *FileNode) AclBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *FileNode) MutateAcl(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *FileNode) LinkName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func FileNodeStart(builder *flatbuffers.Builder) {
	builder.StartObject(10)
}
func FileNodeAddPathId(builder *flatbuffers.Builder, pathId uint32) {
	builder.PrependUint32Slot(0, pathId, 0)
}
func FileNodeAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(name), 0)
}
func FileNodeAddOffsetHeader(builder *flatbuffers.Builder, offsetHeader uint64) {
	builder.PrependUint64Slot(2, offsetHeader, 0)
}
func FileNodeAddOffsetData(builder *flatbuffers.Builder, offsetData uint64) {
	builder.PrependUint64Slot(3, offsetData, 0)
}
func FileNodeAddSize(builder *flatbuffers.Builder, size uint64) {
	builder.PrependUint64Slot(4, size, 0)
}
func FileNodeAddMtime(builder *flatbuffers.Builder, mtime int64) {
	builder.PrependInt64Slot(5, mtime, 0)
}
func FileNodeAddMetadataId(builder *flatbuffers.Builder, metadataId uint32) {
	builder.PrependUint32Slot(6, metadataId, 0)
}
func FileNodeAddXattrs(builder *flatbuffers.Builder, xattrs flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(7, flatbuffers.UOffsetT(xattrs), 0)
}
func FileNodeStartXattrsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func FileNodeAddAcl(builder *flatbuffers.Builder, acl flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(8, flatbuffers.UOffsetT(acl), 0)
}
func FileNodeStartAclVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func FileNodeAddLinkName(builder *flatbuffers.Builder, linkName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(9, flatbuffers.UOffsetT(linkName), 0)
}
func FileNodeEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
