// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package arcidx

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MetadataTuple struct {
	_tab flatbuffers.Struct
}

func (rcv *MetadataTuple) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MetadataTuple) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *MetadataTuple) Mode() uint32 {
	return rcv._tab.GetUint32(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *MetadataTuple) MutateMode(n uint32) bool {
	return rcv._tab.MutateUint32(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *MetadataTuple) Uid() uint32 {
	return rcv._tab.GetUint32(rcv._tab.Pos + flatbuffers.UOffsetT(4))
}
func (rcv *MetadataTuple) MutateUid(n uint32) bool {
	return rcv._tab.MutateUint32(rcv._tab.Pos+flatbuffers.UOffsetT(4), n)
}

func (rcv *MetadataTuple) Gid() uint32 {
	return rcv._tab.GetUint32(rcv._tab.Pos + flatbuffers.UOffsetT(8))
}
func (rcv *MetadataTuple) MutateGid(n uint32) bool {
	return rcv._tab.MutateUint32(rcv._tab.Pos+flatbuffers.UOffsetT(8), n)
}

func (rcv *MetadataTuple) RecursionDepth() uint32 {
	return rcv._tab.GetUint32(rcv._tab.Pos + flatbuffers.UOffsetT(12))
}
func (rcv *MetadataTuple) MutateRecursionDepth(n uint32) bool {
	return rcv._tab.MutateUint32(rcv._tab.Pos+flatbuffers.UOffsetT(12), n)
}

func (rcv *MetadataTuple) TypeFlag() byte {
	return rcv._tab.GetByte(rcv._tab.Pos + flatbuffers.UOffsetT(16))
}
func (rcv *MetadataTuple) MutateTypeFlag(n byte) bool {
	return rcv._tab.MutateByte(rcv._tab.Pos+flatbuffers.UOffsetT(16), n)
}

func (rcv *MetadataTuple) IsTar() bool {
	return rcv._tab.GetBool(rcv._tab.Pos + flatbuffers.UOffsetT(17))
}
func (rcv *MetadataTuple) MutateIsTar(n bool) bool {
	return rcv._tab.MutateBool(rcv._tab.Pos+flatbuffers.UOffsetT(17), n)
}

func (rcv *MetadataTuple) IsSparse() bool {
	return rcv._tab.GetBool(rcv._tab.Pos + flatbuffers.UOffsetT(18))
}
func (rcv *MetadataTuple) MutateIsSparse(n bool) bool {
	return rcv._tab.MutateBool(rcv._tab.Pos+flatbuffers.UOffsetT(18), n)
}

func (rcv *MetadataTuple) IsGenerated() bool {
	return rcv._tab.GetBool(rcv._tab.Pos + flatbuffers.UOffsetT(19))
}
func (rcv *MetadataTuple) MutateIsGenerated(n bool) bool {
	return rcv._tab.MutateBool(rcv._tab.Pos+flatbuffers.UOffsetT(19), n)
}

func CreateMetadataTuple(builder *flatbuffers.Builder, mode uint32, uid uint32, gid uint32, recursionDepth uint32, typeFlag byte, isTar bool, isSparse bool, isGenerated bool) flatbuffers.UOffsetT {
	builder.Prep(4, 20)
	builder.PrependBool(isGenerated)
	builder.PrependBool(isSparse)
	builder.PrependBool(isTar)
	builder.PrependByte(typeFlag)
	builder.PrependUint32(recursionDepth)
	builder.PrependUint32(gid)
	builder.PrependUint32(uid)
	builder.PrependUint32(mode)
	return builder.Offset()
}
