// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package arcidx

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Xattr struct {
	_tab flatbuffers.Table
}

func GetRootAsXattr(buf []byte, offset flatbuffers.UOffsetT) *Xattr {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Xattr{}
	x.Init(buf, n+offset)
	return x
}

func FinishXattrBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsXattr(buf []byte, offset flatbuffers.UOffsetT) *Xattr {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Xattr{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedXattrBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Xattr) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Xattr) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Xattr) KeyId() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Xattr) MutateKeyId(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *Xattr) Value(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *Xattr) ValueLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *Xattr) ValueBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Xattr) MutateValue(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func XattrStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func XattrAddKeyId(builder *flatbuffers.Builder, keyId uint32) {
	builder.PrependUint32Slot(0, keyId, 0)
}
func XattrAddValue(builder *flatbuffers.Builder, value flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(value), 0)
}
func XattrStartValueVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func XattrEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
